version: '3'
services:

  # = MongoDB ======================================================

  pcr-covid19-mongo:
    container_name: spring-cache-redis
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: a532h456
    ports:
      - 27017:27017

  # = Redis ========================================================

  redis-server:
    container_name: redis
    image: 'redis'
    ports:
      - "6379:6379"