spring:
  application:
    name: can
  data:
    mongodb:
      uri: mongodb://mongoadmin:a532h456@localhost:27017/auth_template?authSource=admin&readPreference=primary&directConnection=true&ssl=false
  redis:
    host: localhost
    port: 6379
  cache:
    type: redis
    redis:
      time-to-live: 60000
    cache-names: Books

